apiVersion: v2
name: among-clusters-headlamp
description: Installer for the read-only AmongClusters Headlamp plugin
type: application
version: 0.3.7
appVersion: 0.3.7
annotations: {artifacthub.io/category: monitoring-logging, artifacthub.io/license: Apache-2.0}
