{{- if .Values.ciliumPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata: {name: among-clusters-hub-gateway}
spec:
  endpointSelector: {matchLabels: {app.kubernetes.io/name: among-clusters-hub}}
  ingress:
    - fromEntities: [ingress]
      toPorts:
        - ports:
            - {port: "8080", protocol: TCP}
{{- end }}
