apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: among-clusters-hub}
spec:
  podSelector: {matchLabels: {app.kubernetes.io/name: among-clusters-hub}}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}
        {{- if .Values.managedAccess.enabled }}
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: {{ .Values.managedAccess.broker.namespace }}}}
        {{- end }}
      ports: [{protocol: TCP, port: 8080}]
  egress:
    - to:
        - ipBlock: {cidr: 0.0.0.0/0}
      ports: [{protocol: TCP, port: 443}]
    - to:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}]
