import {registerRoute,registerSidebarEntry} from '@kinvolk/headlamp-plugin/lib';
import {SectionBox,StatusLabel,Table} from '@kinvolk/headlamp-plugin/lib/components/common';
import {makeCustomResourceClass} from '@kinvolk/headlamp-plugin/lib/lib/k8s/crd';
import {Alert,Box,Chip,Typography} from '@mui/material';
const resource=(kind:string,singular:string,plural:string)=>makeCustomResourceClass({apiInfo:[{group:'peering.re8ch.com',version:'v1alpha1'}],kind,pluralName:plural,singularName:singular,isNamespaced:true});
const ClusterIdentity=resource('ClusterIdentity','clusteridentity','clusteridentities');const Peer=resource('Peer','peer','peers');const Link=resource('AuthenticatedLink','authenticatedlink','authenticatedlinks');const Advertisement=resource('ServiceAdvertisement','serviceadvertisement','serviceadvertisements');const Imported=resource('ImportedService','importedservice','importedservices');const Grant=resource('ManagedAccessGrant','managedaccessgrant','managedaccessgrants');
const state=(x:any)=>x?.status?.state||'Pending';const label=(value:string)=><StatusLabel status={['Ready','Active'].includes(value)?'success':['Failed','Revoked','Blocked','Expired','Denied'].includes(value)?'error':'warning'}>{value}</StatusLabel>;
function Dashboard(){const options={} as any;const[identities,e1]=ClusterIdentity.useList(options);const[peers,e2]=Peer.useList(options);const[links,e3]=Link.useList(options);const[ads,e4]=Advertisement.useList(options);const[imports,e5]=Imported.useList(options);const[grants,e6]=Grant.useList(options);const errors=[e1,e2,e3,e4,e5,e6].filter(Boolean);return <Box sx={{p:2}}><Typography variant="h4">AmongClusters</Typography><Typography color="text.secondary">Sovereign Cluster Peering — Mesh clusters you don’t control.</Typography><Alert severity="info" sx={{my:2}}>只读观察面：不会创建 Peer、接受服务、读取 Credential Broker 引用或操作远端 Kubernetes。</Alert>{errors.length>0&&<Alert severity="error">部分 peering.re8ch.com 资源不可读；请检查当前用户的 view RBAC。</Alert>}<SectionBox title={`Trust domains (${(identities||[]).length})`}><Table data={identities||[]} columns={[{header:'Cluster',accessorFn:(x:any)=>`${x.metadata.namespace}/${x.spec?.clusterID||x.metadata.name}`},{header:'SPIFFE ID',accessorFn:(x:any)=>x.spec?.spiffeID||'-'},{header:'Bundle',accessorFn:(x:any)=><Typography variant="caption">{x.spec?.bundleDigest||'-'}</Typography>},{header:'State',accessorFn:(x:any)=>label(state(x))}] as any}/></SectionBox><SectionBox title={`Peers / authenticated links (${(peers||[]).length} / ${(links||[]).length})`}><Table data={links||[]} columns={[{header:'Link',accessorFn:(x:any)=>`${x.metadata.namespace}/${x.metadata.name}`},{header:'Peer',accessorFn:(x:any)=>x.spec?.peerRef||'-'},{header:'Transport',accessorFn:(x:any)=><Chip size="small" label={x.spec?.transport||'-'}/>},{header:'Gateways',accessorFn:(x:any)=>`${x.spec?.localGateway||'-'} → ${x.spec?.remoteGateway||'-'}`},{header:'Latency',accessorFn:(x:any)=>x.status?.latencyMillis===null||x.status?.latencyMillis===undefined?'-':`${x.status.latencyMillis} ms`},{header:'State',accessorFn:(x:any)=><Box>{label(state(x))}<Typography variant="caption" display="block">{x.status?.reason||''}</Typography></Box>}] as any}/></SectionBox><SectionBox title={`Service advertisements / imports (${(ads||[]).length} / ${(imports||[]).length})`}><Table data={ads||[]} columns={[{header:'Service identity',accessorFn:(x:any)=>x.spec?.serviceIdentity||'-'},{header:'Class',accessorFn:(x:any)=>x.spec?.serviceClass||'-'},{header:'Contract',accessorFn:(x:any)=>`${x.spec?.protocol||'-'}:${x.spec?.port||'-'}`},{header:'Targets',accessorFn:(x:any)=>(x.spec?.targetPeers||[]).join(', ')},{header:'Expires',accessorFn:(x:any)=>x.status?.expiresAt||'-'},{header:'State',accessorFn:(x:any)=>label(state(x))}] as any}/></SectionBox><Typography variant="caption" color="text.secondary">ManagedAccessGrant: {(grants||[]).length}. Credential values are intentionally never rendered.</Typography></Box>}
registerSidebarEntry({name:'among-clusters',url:'/among-clusters',icon:'mdi:transit-connection-variant',parent:'',label:'AmongClusters'});registerRoute({path:'/among-clusters',sidebar:'among-clusters',name:'AmongClusters',component:()=> <Dashboard/>});
