apiVersion: v1
kind: ServiceAccount
metadata: {name: among-clusters-agent}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: among-clusters-agent-observer}
rules:
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: among-clusters-agent-observer}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: among-clusters-agent-observer}
subjects: [{kind: ServiceAccount, name: among-clusters-agent, namespace: "{{ .Release.Namespace }}"}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: among-clusters-agent-identity}
rules:
  - apiGroups: [""]
    resources: [secrets]
    resourceNames: ["{{ .Values.identitySecret }}"]
    verbs: [get, update]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create]
  {{- if .Values.managedAccess.enabled }}
  - apiGroups: [""]
    resources: [serviceaccounts/token]
    resourceNames: ["{{ .Values.managedAccess.serviceAccountName }}"]
    verbs: [create]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: among-clusters-agent-identity}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: among-clusters-agent-identity}
subjects: [{kind: ServiceAccount, name: among-clusters-agent}]
